version: '3.5'

services:
  bitstamp-prov:
    container_name: bitstamp-prov
    build: ./dataprovs/bitstamp
    volumes:
      - "./dataprovs/bitstamp/flesh:/srv"
      - "/srv/.venv"
      - "./lib/shengren:/srv/.venv/lib/python3.7/site-packages/shengren"
    command: "tail -f /dev/null"
    restart: always
    networks:
      - network

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    networks:
      - network

  bitstamp-mock:
    container_name: bitstamp-mock
    build: ./mockexchs/bitstamp
    volumes:
      - "./mockexchs/bitstamp/flesh:/srv"
      - "/srv/.venv"
      - "./lib/shengren:/srv/.venv/lib/python3.7/site-packages/shengren"
    command: "tail -f /dev/null"
    restart: always
    networks:
      - network

  lib:
    container_name: lib
    build: ./lib
    volumes:
      - "./lib:/srv"
      - "/srv/.venv"
    command: "tail -f /dev/null"
    restart: always
    networks:
      - network

networks:
  network:
