version: '3.5'

services:
  bitstamp:
    container_name: bitstamp
    build: ./dataprovs/bitstamp
    volumes:
      - "./dataprovs/bitstamp/flesh:/srv"
      - "/srv/.venv"
    command: "tail -f /dev/null"
    restart: always

    networks:
      - network

  influxdb:
    image: influxdb:latest
    container_name: influxdb

    networks:
      - network

  lib:
    container_name: lib
    build: ./lib
    volumes:
      - "./lib:/srv"
      - "/srv/.venv"
    command: "tail -f /dev/null"
    restart: always

    networks:
      - network

  flask_srv:
    container_name: flask_srv
    build: ./flask_srv
    volumes:
      - "./flask_srv/flesh:/srv"
      - "./lib/shengren:/srv/shengren"
      - "/srv/.venv"
    command: "pipenv run flask run --host=0.0.0.0 --port=5000"
    restart: always
    ports:
      - "5000"

    networks:
      - network

  django_srv:
    container_name: django_srv
    build: ./django_srv
    volumes:
      - "./django_srv/flesh:/srv"
      - "./lib/shengren:/srv/shengren"
      - "/srv/.venv"
    command: "pipenv run flask run --host=0.0.0.0 --port=5000"
    restart: always
    ports:
      - "5000"

    networks:
      - network

networks:
  network:
