# motd
motd:
  src_path: roles/motd/motd/motd

# bind, dns
bind_allow_query:
  - any
bind_listen_ipv6:
  - any
bind_acls:
  - name: acl1
    match_list:
      - 172.17.8.0/16
bind_zone_master_server_ip: 172.17.8.100
bind_zone_name_servers:
  - ns
bind_listen_ipv4:
  - any
bind_forwarders:
  - '8.8.8.8'
  - '8.8.4.4'
bind_recursion: true
bind_check_names: 'master ignore'
bind_zone_minimum_ttl: "2D"
bind_zone_ttl: "2W"
bind_zone_time_to_refresh: "2D"
bind_zone_time_to_retry: "2H"
bind_zone_time_to_expire: "2W"
