version: '3.5'

services:
  pypi:
    container_name: pypi
    hostname: pypi.pi

    build: .

    command: pypi-server -p 80 -P /srv/storage/pypi/passwords/.htpasswd /srv/storage/pypi/packages
    #command: sleep 100000
    restart: always

    network_mode: bridge

    volumes:
      - type: volume
        source: pypi
        target: /srv/storage/pypi/
        volume:
          nocopy: true

volumes:
  pypi:
